project: vila
group: stage1
run_name: so101_stage1
output_root: outputs/stage1
seed: 0

lapo:
  num_epochs: 100
  batch_size: 16
  camera_num: 4 # TODO: update for your dataset if needed
  view_keys: [] # TODO: fill in dataset-specific camera ids
  views_per_instance: 8
  future_obs_offset: 10
  latent_action_dim: 512
  learning_rate: 0.0001
  contrastive_loss_coef: 1.0
  labeled_loss_coef: 0.0
  infonce_temperature: 1.0
  weighted_infonce_beta: 0.05
  alignment_loss_coef: 1.0
  use_aug: true
  frame_stack: 1
  resize_size: 128
  encoder_scale: 1
  encoder_num_res_blocks: 2
  encoder_deep: false
  encoder_norm_out: false
  action_key: delta_ee
  filter_noop: false
  data_path: "$ROBOTICS_DATA_ROOT/so101_drawer/so101_drawer.hdf5"
  num_trajectories_to_load: 200

bc:
  num_epochs: 100
  batch_size: 256
  learning_rate: 0.00001
  fixed_offset: 10
  frame_stack: 1
  camera_num: 4 # TODO: update for your dataset if needed
  view_keys: [] # TODO: fill in dataset-specific camera ids
  views_per_instance: 1
  use_aug: false
  encoder_scale: 32
  encoder_num_res_blocks: 2
  encoder_deep: false
  resize_size: 128
  action_key: delta_ee
  filter_noop: false
  data_path: "$ROBOTICS_DATA_ROOT/so101_drawer/so101_drawer.hdf5"
  num_trajectories_to_load: 200
